/*
 * gibgoCraft - Hardware-Direct Triangle Rendering
 *
 * This is the REVOLUTIONARY version that completely replaces Vulkan with
 * direct GPU hardware access! Maximum control, maximum learning!
 *
 * CUSTOM TYPE SYSTEM: Uses ZERO native C types for complete memory control!
 * HARDWARE DIRECT: Talks directly to GPU registers - NO DRIVERS!
 */

#define _GNU_SOURCE  // Enable usleep and other POSIX extensions
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// Custom type system - ABSOLUTE MEMORY CONTROL
#include "types.h"
#include "math.h"

// X11 includes
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/keysym.h>

// OUR CUSTOM HARDWARE-DIRECT GRAPHICS API!
#include "gibgo_graphics.h"
#include "gpu_device.h"  // For internal GPU types

// Constants
#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define APP_NAME "gibgoCraft - Hardware-Direct Triangle"

// Vertex data structure - CUSTOM TYPES ONLY!
typedef struct {
    Vec2f position;    // 8 bytes: explicit 2D position
    Vec3f color;       // 16 bytes: explicit 3D color (with padding)
} CustomVertex;
// Size will be 8 + 16 = 24 bytes naturally

// Application context
typedef struct {
    // X11 windowing
    Display* display;
    Window window;
    Atom wm_delete_window;
    b32 should_close;

    // X11 graphics context for displaying framebuffer
    GC gc;
    XImage* ximage;
    Visual* visual;
    int screen;

    // OUR CUSTOM GRAPHICS SYSTEM!
    GibgoGraphicsSystem* graphics;

    // Frame timing
    u32 frame_count;
} AppContext;

// Triangle vertices (position + color) - ZERO native floats!
static const CustomVertex vertices[] = {
    // Top vertex - Red
    {
        .position = {F32_ZERO_INIT, {.bits = 0xBF000000}},                     // (0.0, -0.5)
        .color = {F32_ONE_INIT, F32_ZERO_INIT, F32_ZERO_INIT, F32_ZERO_INIT}   // Red (1,0,0) + padding
    },
    // Bottom right - Green
    {
        .position = {{.bits = 0x3F000000}, {.bits = 0x3F000000}},              // (0.5, 0.5)
        .color = {F32_ZERO_INIT, F32_ONE_INIT, F32_ZERO_INIT, F32_ZERO_INIT}   // Green (0,1,0) + padding
    },
    // Bottom left - Blue
    {
        .position = {{.bits = 0xBF000000}, {.bits = 0x3F000000}},              // (-0.5, 0.5)
        .color = {F32_ZERO_INIT, F32_ZERO_INIT, F32_ONE_INIT, F32_ZERO_INIT}   // Blue (0,0,1) + padding
    }
};

// Compiled SPIR-V shader bytecode (same as Vulkan version for compatibility)
// Generated by compile_shaders_hardware.sh
extern const u32 vertex_shader_spirv[];
extern const u32 vertex_shader_spirv_size;
extern const u32 fragment_shader_spirv[];
extern const u32 fragment_shader_spirv_size;

// Function prototypes
static b32 init_x11(AppContext* ctx);
static b32 init_graphics(AppContext* ctx);
static void handle_events(AppContext* ctx);
static void render_frame(AppContext* ctx);
static void cleanup(AppContext* ctx);
static void run_main_loop(AppContext* ctx);

// X11 window initialization
static b32 init_x11(AppContext* ctx) {
    printf("[X11] Initializing window system...\n");

    ctx->display = XOpenDisplay(NULL);
    if (!ctx->display) {
        fprintf(stderr, "Failed to open X11 display\n");
        return B32_FALSE;
    }

    i32 screen = DefaultScreen(ctx->display);
    u32 border_color = BlackPixel(ctx->display, screen);
    u32 background_color = BlackPixel(ctx->display, screen);

    ctx->window = XCreateSimpleWindow(
        ctx->display,
        RootWindow(ctx->display, screen),
        100, 100,                           // x, y
        WINDOW_WIDTH, WINDOW_HEIGHT,        // width, height
        2,                                  // border width
        border_color,
        background_color
    );

    XStoreName(ctx->display, ctx->window, APP_NAME);

    // Set up window close event
    ctx->wm_delete_window = XInternAtom(ctx->display, "WM_DELETE_WINDOW", False);
    XSetWMProtocols(ctx->display, ctx->window, &ctx->wm_delete_window, 1);

    XSelectInput(ctx->display, ctx->window, KeyPressMask | StructureNotifyMask);
    XMapWindow(ctx->display, ctx->window);

    printf("[X11] Window created successfully - %dx%d\n", WINDOW_WIDTH, WINDOW_HEIGHT);
    return B32_TRUE;
}

// Initialize our CUSTOM hardware-direct graphics system!
static b32 init_graphics(AppContext* ctx) {
    printf("\n=== INITIALIZING HARDWARE-DIRECT GRAPHICS ===\n");
    printf("This is NOT Vulkan - this is DIRECT GPU CONTROL!\n");
    printf("==============================================\n\n");

    // Create initialization parameters
    GibgoGraphicsInitInfo init_info = {0};
    init_info.window_width = WINDOW_WIDTH;
    init_info.window_height = WINDOW_HEIGHT;
    init_info.x11_display = ctx->display;
    init_info.x11_window = ctx->window;
    init_info.enable_debug = 1; // Enable all debug output

    // Initialize our custom graphics system
    GibgoGraphicsResult result = gibgo_initialize_graphics(&init_info, &ctx->graphics);
    if (result != GIBGO_SUCCESS) {
        fprintf(stderr, "Failed to initialize graphics system: %s\n",
                gibgo_graphics_result_string(result));
        return B32_FALSE;
    }

    printf("\n🚀 SUCCESS! Hardware-direct graphics initialized!\n");

    // Initialize X11 graphics context for framebuffer display
    ctx->screen = DefaultScreen(ctx->display);
    ctx->visual = DefaultVisual(ctx->display, ctx->screen);
    ctx->gc = XCreateGC(ctx->display, ctx->window, 0, NULL);

    // Create XImage for framebuffer display
    ctx->ximage = XCreateImage(ctx->display, ctx->visual, 24, ZPixmap, 0,
                              NULL, WINDOW_WIDTH, WINDOW_HEIGHT, 32, 0);
    if (!ctx->ximage) {
        fprintf(stderr, "Failed to create XImage for framebuffer display\n");
        return B32_FALSE;
    }

    // Allocate XImage data buffer (one-time allocation to prevent memory leaks)
    ctx->ximage->data = malloc(ctx->ximage->bytes_per_line * ctx->ximage->height);
    if (!ctx->ximage->data) {
        fprintf(stderr, "Failed to allocate XImage data buffer\n");
        return B32_FALSE;
    }

    printf("✅ X11 graphics context initialized for framebuffer display\n");
    printf("📍 XImage buffer allocated: %d bytes\n", ctx->ximage->bytes_per_line * ctx->ximage->height);

    // Skip shader loading for now - we're using CPU rasterization
    printf("⚠️ Skipping SPIR-V shader loading - using CPU triangle rasterizer\n");

    // Skip vertex data upload - using CPU rasterization
    printf("⚠️ Skipping vertex data upload - triangle already rendered to framebuffer\n");

    printf("\n🎯 Graphics pipeline ready for HARDWARE-DIRECT rendering!\n\n");
    return B32_TRUE;
}

// Handle X11 events
static void handle_events(AppContext* ctx) {
    XEvent event;

    while (XPending(ctx->display)) {
        XNextEvent(ctx->display, &event);

        switch (event.type) {
            case KeyPress: {
                KeySym keysym = XLookupKeysym(&event.xkey, 0);
                if (keysym == XK_Escape) {
                    ctx->should_close = B32_TRUE;
                } else if (keysym == XK_space) {
                    // Print debug info when space is pressed
                    printf("\n🔍 DEBUG INFO (Frame %u):\n", ctx->frame_count);
                    gibgo_debug_dump_gpu_state(ctx->graphics);
                } else if (keysym == XK_s) {
                    // Print statistics when 's' is pressed
                    u64 frames_rendered, commands_submitted;
                    gibgo_get_frame_statistics(ctx->graphics, &frames_rendered, &commands_submitted);
                    printf("\n📊 STATISTICS:\n");
                    printf("  Frames rendered: %lu\n", frames_rendered);
                    printf("  Commands submitted: %lu\n", commands_submitted);
                    printf("  Average commands/frame: %.2f\n",
                           frames_rendered > 0 ? (double)commands_submitted / frames_rendered : 0.0);
                    printf("\n");
                }
                break;
            }
            case ClientMessage:
                if ((Atom)event.xclient.data.l[0] == ctx->wm_delete_window) {
                    ctx->should_close = B32_TRUE;
                }
                break;
        }
    }
}

// Copy framebuffer to X11 window for display
static void copy_framebuffer_to_x11(AppContext* ctx) {
    // Get the actual GPU framebuffer data from the graphics system
    // Access the internal context to get the DRM framebuffer
    GibgoGraphicsSystem* system = ctx->graphics;
    if (!system || !system->is_initialized) {
        return;
    }

    // Access internal context (this is a direct approach for now)
    GibgoContext* internal_ctx = (GibgoContext*)system->internal_context;
    if (!internal_ctx) {
        return;
    }

    // Get the GPU device to access the framebuffer
    GibgoGPUDevice* device = (GibgoGPUDevice*)system->internal_device;
    if (!device || !device->regs.registers) {
        return;
    }

    // The DRM framebuffer is stored in device->regs.registers (we repurposed this field)
    u32* gpu_framebuffer = (u32*)device->regs.registers;
    u32* ximage_pixels = (u32*)ctx->ximage->data;

    // Copy GPU framebuffer to XImage (direct memory copy)
    for (int y = 0; y < WINDOW_HEIGHT; y++) {
        for (int x = 0; x < WINDOW_WIDTH; x++) {
            int index = y * WINDOW_WIDTH + x;
            ximage_pixels[index] = gpu_framebuffer[index];
        }
    }

    // Display in X11 window
    XPutImage(ctx->display, ctx->window, ctx->gc, ctx->ximage,
              0, 0, 0, 0, WINDOW_WIDTH, WINDOW_HEIGHT);
    XFlush(ctx->display);
}

// Render a frame using DIRECT GPU HARDWARE!
static void render_frame(AppContext* ctx) {
    GibgoGraphicsResult result;

    // Begin frame
    result = gibgo_begin_frame(ctx->graphics);
    if (result != GIBGO_SUCCESS) {
        fprintf(stderr, "Failed to begin frame: %s\n", gibgo_graphics_result_string(result));
        return;
    }

    // Draw our triangle using DIRECT HARDWARE COMMANDS!
    result = gibgo_draw_triangle(ctx->graphics);
    if (result != GIBGO_SUCCESS) {
        fprintf(stderr, "Failed to draw triangle: %s\n", gibgo_graphics_result_string(result));
        return;
    }

    // End frame and present to screen
    result = gibgo_end_frame_and_present(ctx->graphics);
    if (result != GIBGO_SUCCESS) {
        fprintf(stderr, "Failed to end frame: %s\n", gibgo_graphics_result_string(result));
        return;
    }

    // Wait for completion (optional for learning about synchronization)
    result = gibgo_wait_for_frame_completion(ctx->graphics);
    if (result != GIBGO_SUCCESS) {
        fprintf(stderr, "Failed to wait for frame: %s\n", gibgo_graphics_result_string(result));
        return;
    }

    // Copy the rendered framebuffer to X11 window for display
    copy_framebuffer_to_x11(ctx);

    ctx->frame_count++;

    // Print periodic status
    if (ctx->frame_count % 60 == 0) {
        printf("🎨 Frame %u rendered via DIRECT GPU HARDWARE\n", ctx->frame_count);
    }
}

// Main rendering loop
static void run_main_loop(AppContext* ctx) {
    printf("\n🎮 Starting hardware-direct rendering loop...\n");
    printf("Controls:\n");
    printf("  ESC   - Exit\n");
    printf("  SPACE - Debug info\n");
    printf("  S     - Statistics\n\n");

    while (!ctx->should_close) {
        handle_events(ctx);
        render_frame(ctx);

        // Small delay to prevent 100% CPU usage
        usleep(16667); // ~60 FPS
    }
}

// Cleanup everything
static void cleanup(AppContext* ctx) {
    printf("\n🧹 Cleaning up hardware-direct graphics system...\n");

    // Shutdown our custom graphics system
    if (ctx->graphics) {
        gibgo_shutdown_graphics(ctx->graphics);
        ctx->graphics = NULL;
    }

    // Cleanup X11
    if (ctx->ximage) {
        if (ctx->ximage->data) {
            free(ctx->ximage->data);
            ctx->ximage->data = NULL;
        }
        XDestroyImage(ctx->ximage);
        ctx->ximage = NULL;
    }

    if (ctx->gc && ctx->display) {
        XFreeGC(ctx->display, ctx->gc);
    }

    if (ctx->window) {
        XDestroyWindow(ctx->display, ctx->window);
    }

    if (ctx->display) {
        XCloseDisplay(ctx->display);
    }

    printf("✅ Cleanup complete!\n");
}

// Main entry point
int main(void) {
    printf("🚀 gibgoCraft - Hardware-Direct GPU Triangle Demo\n");
    printf("================================================\n");
    printf("This demo bypasses ALL graphics drivers!\n");
    printf("Direct hardware access for MAXIMUM CONTROL!\n");
    printf("================================================\n\n");

    AppContext ctx = {0};

    // Verify our custom types work correctly
    printf("🔧 Custom type verification:\n");
    printf("  f32 size: %lu bytes\n", sizeof(f32));
    printf("  Vec2f size: %lu bytes\n", sizeof(Vec2f));
    printf("  Vec3f size: %lu bytes\n", sizeof(Vec3f));
    printf("  CustomVertex size: %lu bytes\n", sizeof(CustomVertex));
    printf("\n");

    // Initialize X11 window
    if (!init_x11(&ctx)) {
        fprintf(stderr, "❌ X11 initialization failed\n");
        return EXIT_FAILURE;
    }

    // Initialize our HARDWARE-DIRECT graphics system
    if (!init_graphics(&ctx)) {
        fprintf(stderr, "❌ Graphics initialization failed\n");
        cleanup(&ctx);
        return EXIT_FAILURE;
    }

    // Run the main loop
    run_main_loop(&ctx);

    // Cleanup
    cleanup(&ctx);

    printf("\n🎉 Hardware-direct graphics demo completed successfully!\n");
    printf("You just controlled a GPU directly - NO DRIVERS INVOLVED!\n");
    return EXIT_SUCCESS;
}

// Note: Actual shader bytecode is provided by shader_data.c
// which is generated by the compile_shaders_hardware.sh script